version: "3.9"

services:
  database_microservices: 
    image: postgres
    container_name: database_microservices
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=backoffice_db
    volumes:
      - pgdata:/data/postgres

  mongo_microservices:
    image: mongo
    container_name: mongo_microservices
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    volumes:
      - mongo-volume:/data/db

  zookeeper_microservices:
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'

  kafka_microservices:
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka_microservices
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "controll-modules:1:1"
    volumes:
      - /var/run/docker.sock:/var/run.docker.sock

  backoffice_app:
    build: ./backoffice
    container_name: backoffice_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/backoffice_app
    links:
      - database_microservices
    depends_on:
      - database_microservices
  
  company_app:
    build: ./company-app
    container_name: company_app
    ports:
      - 4000:4000
    volumes:
      - .:/usr/company_app
    links:
      - mongo_microservices
    depends_on:
      - mongo_microservices
      
volumes:
  pgdata:
    driver: local
  mongo-volume: 
    driver: local

