version: "3.9"

services:
  database_microservices: 
    image: postgres
    container_name: database_microservices
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - pgdata:/data/postgres
  backoffice_app:
    build: ./backoffice
    container_name: backoffice_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/backoffice_app
    links:
      - database_microservices
    depends_on:
      - database_microservices
      
volumes:
  pgdata:
    driver: local
